import Foundation
import HealthKit
import PamNative
public final class HealthModule:NativeModule,@unchecked Sendable{private let store=HKHealthStore();public init(){};public func invoke(method:String,payload:Data,completion:@escaping ModuleCompletion){do{let v=try WireMap.decode(payload);switch method{case"availability":try success(["availability":.integer(HKHealthStore.isHealthDataAvailable() ? 1:2)],completion);case"authorize":try authorize(v,completion);case"needsAuthorization":try needsAuthorization(v,completion);case"read":try read(v,completion);case"write":try write(v,completion);default:failure("Unknown method: \(method)",completion)}}catch{failure(String(describing:error),completion)}}
 private func authorize(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion)throws{let read=try types(v.text("read"));let write=try types(v.text("write"));store.requestAuthorization(toShare:Set(write),read:Set(read)){ok,error in if let error{self.failure(error.localizedDescription,completion)}else if ok{try?self.success([:],completion)}else{self.failure("Health authorization was not completed.",completion)}}}
 private func needsAuthorization(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion)throws{let read=try types(v.text("read"));let write=try types(v.text("write"));store.getRequestStatusForAuthorization(toShare:Set(write),read:Set(read)){status,error in if let error{self.failure(error.localizedDescription,completion)}else{try?self.success(["needed":.flag(status == .shouldRequest)],completion)}}}
 private func read(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion)throws{let code=Int(try v.integer("type"));guard let type=sampleType(code)else{throw HealthError.type};let from=Date(timeIntervalSince1970:Double(try v.integer("fromMillis"))/1000);let to=Date(timeIntervalSince1970:Double(try v.integer("toMillis"))/1000);let query=HKSampleQuery(sampleType:type,predicate:HKQuery.predicateForSamples(withStart:from,end:to),limit:Int(try v.integer("limit")),sortDescriptors:[NSSortDescriptor(key:HKSampleSortIdentifierStartDate,ascending:true)]){_,samples,error in if let error{self.failure(error.localizedDescription,completion);return};let rows=(samples ?? []).map{self.row($0,code:code)};do{let data=try JSONSerialization.data(withJSONObject:rows);try self.success(["json":.text(String(data:data,encoding:.utf8) ?? "[]")],completion)}catch{self.failure(String(describing:error),completion)}};store.execute(query)}
 private func write(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion)throws{let code=Int(try v.integer("type"));guard let type=sampleType(code)else{throw HealthError.type};let start=Date(timeIntervalSince1970:Double(try v.integer("startMillis"))/1000);let end=Date(timeIntervalSince1970:Double(try v.integer("endMillis"))/1000);let value=try v.decimal("value");let sample:HKSample;if code==5{sample=HKCategorySample(type:type as!HKCategoryType,value:HKCategoryValueSleepAnalysis.asleepUnspecified.rawValue,start:start,end:end)}else{sample=HKQuantitySample(type:type as!HKQuantityType,quantity:HKQuantity(unit:unit(code),doubleValue:value),start:start,end:end)};store.save(sample){ok,error in if let error{self.failure(error.localizedDescription,completion)}else if ok{try?self.success([:],completion)}else{self.failure("Health sample was not saved.",completion)}}}
 private func types(_ json:String)throws->[HKSampleType]{let codes=try JSONDecoder().decode([Int].self,from:Data(json.utf8));return try codes.map{guard let type=sampleType($0)else{throw HealthError.type};return type}}
 private func sampleType(_ code:Int)->HKSampleType?{switch code{case 1:return HKQuantityType.quantityType(forIdentifier:.stepCount);case 2:return HKQuantityType.quantityType(forIdentifier:.heartRate);case 3:return HKQuantityType.quantityType(forIdentifier:.bodyMass);case 4:return HKQuantityType.quantityType(forIdentifier:.activeEnergyBurned);case 5:return HKCategoryType.categoryType(forIdentifier:.sleepAnalysis);default:return nil}}
 private func unit(_ code:Int)->HKUnit{switch code{case 1:return.count();case 2:return HKUnit.count().unitDivided(by:.minute());case 3:return.gramUnit(with:.kilo);case 4:return.kilocalorie();default:return.count()}}
 private func row(_ sample:HKSample,code:Int)->[String:Any]{let value:Double;if let q=sample as?HKQuantitySample{value=q.quantity.doubleValue(for:unit(code))}else{value=sample.endDate.timeIntervalSince(sample.startDate)/60};return["id":sample.uuid.uuidString,"type":code,"value":value,"startMillis":Int64(sample.startDate.timeIntervalSince1970*1000),"endMillis":Int64(sample.endDate.timeIntervalSince1970*1000),"source":sample.sourceRevision.source.bundleIdentifier]}
 private func success(_ values:[String:WireValue]=[:],_ completion:ModuleCompletion)throws{completion(.success,try WireMap.encode(values))};private func failure(_ m:String,_ completion:ModuleCompletion){completion(.failure,Data(m.prefix(1024).utf8))}}
private enum HealthError:Error{case type};private extension Dictionary where Key==String,Value==WireValue{func text(_ k:String)throws->String{guard case let.text(v)?=self[k]else{throw HealthError.type};return v};func integer(_ k:String)throws->Int64{guard case let.integer(v)?=self[k]else{throw HealthError.type};return v};func decimal(_ k:String)throws->Double{switch self[k]{case let.decimal(v)?:return v;case let.integer(v)?:return Double(v);default:throw HealthError.type}}}
