package dev.pam.health
import android.app.Activity
import android.content.Context
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.PermissionController
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.*
import androidx.health.connect.client.records.metadata.Metadata
import androidx.health.connect.client.request.ReadRecordsRequest
import androidx.health.connect.client.time.TimeRangeFilter
import androidx.health.connect.client.units.Energy
import androidx.health.connect.client.units.Mass
import dev.pam.nativeapp.modules.*
import dev.pam.nativeapp.protocol.*
import kotlinx.coroutines.*
import org.json.JSONArray
import org.json.JSONObject
import java.time.Instant
import kotlin.reflect.KClass
class HealthModule(private val context:Context):NativeModule{private val activity=context as? Activity;private val scope=CoroutineScope(SupervisorJob()+Dispatchers.IO);override fun invoke(method:String,payload:ByteArray,completion:ModuleCompletion){val v=runCatching{WireMap.decode(payload)}.getOrElse{completion.fail(it);return};when(method){"availability"->completion.ok(mapOf("availability" to WireValue.Integer(when(HealthConnectClient.getSdkStatus(context)){HealthConnectClient.SDK_AVAILABLE->1;HealthConnectClient.SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED->3;else->2})));"authorize"->authorize(v,completion);else->scope.launch{runCatching{when(method){"needsAuthorization"->needsAuthorization(v);"read"->read(v);"write"->write(v);else->error("Unknown method: $method")}}.onSuccess{completion.ok(it)}.onFailure{completion.fail(it)}}}}
 private fun client()=HealthConnectClient.getOrCreate(context)
 private fun authorize(v:Map<String,WireValue>,completion:ModuleCompletion){val permissions=permissions(v);val a=activity;if(a==null){completion.fail(IllegalStateException("Health authorization requires an Activity context."));return};runCatching{a.startActivity(PermissionController.createRequestPermissionResultContract().createIntent(a,permissions));completion.ok()}.onFailure{completion.fail(it)}}
 private suspend fun needsAuthorization(v:Map<String,WireValue>):Map<String,WireValue>{val expected=permissions(v);return mapOf("needed" to WireValue.Flag(!client().permissionController.getGrantedPermissions().containsAll(expected)))}
 private suspend fun read(v:Map<String,WireValue>):Map<String,WireValue>{val type=v.integer("type").toInt();val from=Instant.ofEpochMilli(v.integer("fromMillis"));val to=Instant.ofEpochMilli(v.integer("toMillis"));val limit=v.integer("limit").toInt();val rows=when(type){1->client().readRecords(ReadRecordsRequest(StepsRecord::class,TimeRangeFilter.between(from,to),pageSize=limit)).records.map{row(it.metadata.id,1,it.count.toDouble(),it.startTime,it.endTime,it.metadata.dataOrigin.packageName)};2->client().readRecords(ReadRecordsRequest(HeartRateRecord::class,TimeRangeFilter.between(from,to),pageSize=limit)).records.flatMap{record->record.samples.map{row(record.metadata.id,2,it.beatsPerMinute.toDouble(),it.time,it.time,record.metadata.dataOrigin.packageName)}};3->client().readRecords(ReadRecordsRequest(WeightRecord::class,TimeRangeFilter.between(from,to),pageSize=limit)).records.map{row(it.metadata.id,3,it.weight.inKilograms,it.time,it.time,it.metadata.dataOrigin.packageName)};4->client().readRecords(ReadRecordsRequest(ActiveCaloriesBurnedRecord::class,TimeRangeFilter.between(from,to),pageSize=limit)).records.map{row(it.metadata.id,4,it.energy.inKilocalories,it.startTime,it.endTime,it.metadata.dataOrigin.packageName)};5->client().readRecords(ReadRecordsRequest(SleepSessionRecord::class,TimeRangeFilter.between(from,to),pageSize=limit)).records.map{row(it.metadata.id,5,(it.endTime.toEpochMilli()-it.startTime.toEpochMilli())/60000.0,it.startTime,it.endTime,it.metadata.dataOrigin.packageName)};else->error("Unsupported health type")};return mapOf("json" to WireValue.Text(JSONArray(rows).toString()))}
 private suspend fun write(v:Map<String,WireValue>):Map<String,WireValue>{val type=v.integer("type").toInt();val value=v.decimal("value");val start=Instant.ofEpochMilli(v.integer("startMillis"));val end=Instant.ofEpochMilli(v.integer("endMillis"));val metadata=Metadata.manualEntry(clientRecordId=v.text("id").ifEmpty{java.util.UUID.randomUUID().toString()});val record:Record=when(type){1->StepsRecord(start,null,end,null,value.toLong(),metadata);2->HeartRateRecord(start,null,end,null,listOf(HeartRateRecord.Sample(start,value.toLong())),metadata);3->WeightRecord(start,null,Mass.kilograms(value),metadata);4->ActiveCaloriesBurnedRecord(start,null,end,null,Energy.kilocalories(value),metadata);5->SleepSessionRecord(start,null,end,null,metadata,null,null);else->error("Unsupported health type")};client().insertRecords(listOf(record));return emptyMap()}
 private fun permissions(v:Map<String,WireValue>):Set<String>{val result=mutableSetOf<String>();val read=JSONArray(v.text("read"));for(i in 0 until read.length())result+=HealthPermission.getReadPermission(record(read.getInt(i)));val write=JSONArray(v.text("write"));for(i in 0 until write.length())result+=HealthPermission.getWritePermission(record(write.getInt(i)));return result};private fun record(type:Int):KClass<out Record> = when(type){1->StepsRecord::class;2->HeartRateRecord::class;3->WeightRecord::class;4->ActiveCaloriesBurnedRecord::class;5->SleepSessionRecord::class;else->error("Unsupported health type")};private fun row(id:String,type:Int,value:Double,start:Instant,end:Instant,source:String)=JSONObject().put("id",id).put("type",type).put("value",value).put("startMillis",start.toEpochMilli()).put("endMillis",end.toEpochMilli()).put("source",source);private fun Map<String,WireValue>.text(k:String)=(get(k)as?WireValue.Text)?.value.orEmpty();private fun Map<String,WireValue>.integer(k:String)=(get(k)as?WireValue.Integer)?.value?:0;private fun Map<String,WireValue>.decimal(k:String)=when(val x=get(k)){is WireValue.Decimal->x.value;is WireValue.Integer->x.value.toDouble();else->0.0};private fun ModuleCompletion.ok(v:Map<String,WireValue> = emptyMap())=complete(ModuleResultStatus.SUCCESS,WireMap.encode(v));private fun ModuleCompletion.fail(e:Throwable)=complete(ModuleResultStatus.FAILURE,e.message.orEmpty().take(1024).toByteArray())}
